[package]
name = "i3-focus-last"
version = "0.4.0"
authors = ["lbonn"]
description = "Focus last window on i3"
license = "MIT"
repository = "https://github.com/lbonn/i3-focus-last"
edition = "2018"

[dependencies]
swayipc = "2.7.2"
gumdrop = "0.8.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
